Algoritmo "Exercício1(c)"
// Descrição   : Consumo médio
// Autor(a)    : Charles Rodrigo Alves de Souza
// Data atual  : 03/10/2020
Var
   dist,comb,cmedio:real
   //declaração de variáveis para distância, combustível e consumo médio//

Inicio
      Escreval("Informe a distância(km):")
      leia(dist)
      Escreval("Informe o total de combustível(I):")
      leia(comb)
      cmedio<-dist/comb //O valor distância é dividio pelo quantidade de combustível//
      Escreval("O consumo médio é:", cmedio)
Fimalgoritmo