Algoritmo "Exercício3(B)"

// Descrição   : Data e dia da semana
// Autor(a)    : Charles Rodrigo Alves de Souza
// Data atual  : 02/10/2020
//Infelizmente não consegui pensar em outra maneira
Var
   data,dsemana:Inteiro

Inicio
      Escreval("Entre com uma data com dia/mês/ano:")
      Leia(data)
      Escolha(data)
      Caso 1
           Escreva("Segunda-feira")
      Caso 2
           Escreva("Terça-feira")
      Caso 3
           Escreva("Quarta-feira")
      Caso 4
           Escreva("quinta-feira")
      Caso 5
           Escreva("Sexta-feira")
      Caso 6
           Escreva("Sábado")
      Caso 7
           Escreva("Domingo")
      Caso 8
           Escreva("Segunda-feira")
      Caso 9
           Escreva("Terça-feira")
      Caso 10
           Escreva("Quarta-feira")
      Caso 11
           Escreva("quinta-feira")
      Caso 12
           Escreva("Sexta-feira")
      Caso 13
           Escreva("Sábado")
      Caso 14
           Escreva("Domingo")
      Caso 15
           Escreva("Segunda-feira")
      Caso 16
           Escreva("Terça-feira")
      Caso 17
           Escreva("Quarta-feira")
      Caso 18
           Escreva("quinta-feira")
      Caso 19
           Escreva("Sexta-feira")
      Caso 20
           Escreva("Sábado")
      Caso 21
           Escreva("Domingo")
      Caso 22
           Escreva("Segunda-feira")
      Caso 23
           Escreva("Terça-feira")
      Caso 24
           Escreva("Quarta-feira")
      Caso 25
           Escreva("quinta-feira")
      Caso 26
           Escreva("Sexta-feira")
      Caso 27
           Escreva("Sábado")
      Caso 28
           Escreva("Domingo")
      Caso 29
           Escreva("Segunda-feira")
      Caso 30
           Escreva("Terça-feira")
      Caso 31
           Escreva("Quarta-feira")
      FimEscolha
Fimalgoritmo
