Algoritmo "Exercício1(a)"
// Descrição   : Cálculo da área
// Autor(a)    : Charles Rodrigo Alves de Souza
// Data atual  : 03/10/2020
Var
a, b, h:real //Atricuição de variáveis


Inicio
      Escreval("Digite a medida da base:")
      Leia(b)
      Escreval("Digite a madida da altura:")
      Leia(h)
      a<- b*h //Atribuição do valor de "a" a partir da fórmula correspondente.
      Escreval("A área é", a)
Fimalgoritmo