Algoritmo "Exercício1(b)"
// Descrição   : Conversor de centímetros para polegadas
// Autor(a)    : Charles Rodrigo Alves de Souza
// Data atual  : 03/10/2020
Var
   c,p:real //Variáveis (c) Centímetros e (p)polegadas//

Inicio
      Escreval("***Conversor de (c) para (p)***")
      Escreval("Informe a medida em centímetros:")
      leia(c)
      p<-c/2.54 //Valor atribuido a p a partir da formula de conversão//
      Escreval("O valor em centímetros convertido em polegadas é:", p) //Impressão de resultados//
Fimalgoritmo